"use client";
import {useEffect,useState} from "react";
export default function Hosting(){const[sites,setSites]=useState<any[]>([]);const[msg,setMsg]=useState("");const[loading,setLoading]=useState(true);
async function load(){const r=await fetch("/api/hosting/sites");const x=await r.json();setSites(x.sites||[]);setLoading(false)}
useEffect(()=>{load()},[]);
async function create(){const slug=prompt("Sous-domaine (ex: monentreprise)");if(!slug)return;const r=await fetch("/api/hosting/sites",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({slug,title:"Mon site Bickri"})});const x=await r.json();setMsg(x.error||"Site créé.");load()}
async function configure(s:any){const repo=prompt("Dépôt GitHub",s.repository_url||"");if(repo===null)return;const custom=prompt("Domaine personnalisé (facultatif)",s.custom_domain||"");if(custom===null)return;const r=await fetch("/api/hosting/config",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:s.id,repository_url:repo,branch:"main",framework:"nextjs",build_command:"npm run build"})});const a=await r.json();if(!r.ok){setMsg(a.error||"Configuration impossible.");return}if(custom){const d=await fetch("/api/domains/custom",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:s.id,custom_domain:custom})});const b=await d.json();if(!d.ok){setMsg(b.error||"Domaine impossible à enregistrer.");return}}setMsg("Configuration enregistrée.");load()}
async function deploy(s:any){if(!s.repository_url){setMsg("Configurez d'abord un dépôt GitHub.");return}setMsg("Déploiement en cours…");const r=await fetch("/api/deployments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({site_id:s.id,repository_url:s.repository_url,branch:s.branch||"main",framework:s.framework||"nextjs",build_command:s.build_command||"npm run build"})});const x=await r.json();setMsg(r.ok||r.status===202?"Déploiement lancé. Votre site sera mis à jour automatiquement.":(x.error||"Déploiement impossible."));load()}
return <main className="hero"><div className="container"><nav className="nav"><a className="brand" href="/">Bickri <span>Domains</span></a><a className="badge" href="/dashboard">TABLEAU DE BORD</a></nav><section style={{padding:"55px 0"}}><div className="eyebrow">HOSTING BICKRI</div><h1 className="title" style={{fontSize:"clamp(38px,6vw,64px)"}}>Vos sites, domaines et déploiements au même endroit.</h1><button className="button" style={{height:52}} onClick={create}>+ Créer un site</button>{msg&&<div className="authMsg" style={{marginTop:18}}>{msg}</div>}{loading?<p className="muted">Chargement…</p>:<div className="results">{sites.map(s=><article className="domainCard" key={s.id}><div><div className="domainName">{s.title}</div><div className="available">{s.host}</div><p className="muted" style={{margin:"8px 0"}}>{s.custom_domain||"Aucun domaine personnalisé"} · DNS {s.dns_status} · SSL {s.ssl_status}</p></div><div className="domainRight"><button className="button" style={{height:44}} onClick={()=>configure(s)}>Configurer</button>{s.repository_url&&<button className="button" style={{height:44,marginLeft:8}} onClick={()=>deploy(s)}>Déployer</button>}<a className="button" style={{height:44,marginLeft:8,textDecoration:"none"}} href={`/sites/${s.slug}`} target="_blank" rel="noreferrer">Voir le site</a></div></article>)}</div>}</section></div></main>}
