"use client";import{useEffect,useState}from"react";
export default function Dashboard(){const[cart,setCart]=useState<any[]>([]);const[domains,setDomains]=useState<any[]>([]);const[sites,setSites]=useState<any[]>([]);const[msg,setMsg]=useState("");const[tab,setTab]=useState("domains");
async function load(){const[a,b,c]=await Promise.all([fetch("/api/cart"),fetch("/api/domains"),fetch("/api/hosting/sites")]);setCart((await a.json()).items||[]);setDomains((await b.json()).domains||[]);setSites((await c.json()).sites||[])}useEffect(()=>{load()},[]);
async function remove(domain:string){await fetch("/api/cart?domain="+encodeURIComponent(domain),{method:"DELETE"});load()}async function checkout(){const r=await fetch("/api/checkout",{method:"POST"});const x=await r.json();setMsg(x.message||x.error||"Commande créée.");load()}async function toggle(id:string,key:string,value:boolean){await fetch("/api/domains",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,[key]:!value})});load()}async function addSite(){const slug=prompt("Choisissez votre sous-domaine");if(!slug)return;const r=await fetch("/api/hosting/sites",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({slug,title:"Mon site Bickri"})});const x=await r.json();setMsg(x.site?"Site créé : "+x.site.host:(x.error||"Erreur"));load()}
const tabs=[["domains","Mes domaines"],["cart","Panier"],["hosting","Hébergement"],["transfer","Transfert"],["dns","DNS"],["billing","Factures"]];
return <main style={{minHeight:"100vh",background:"#07152f",color:"#fff",padding:24}}><div style={{maxWidth:1150,margin:"auto"}}><div style={{display:"flex",justifyContent:"space-between",flexWrap:"wrap"}}><div><b style={{color:"#d4aa45"}}>BICKRI DOMAINS</b><h1>Espace client</h1><p style={{color:"#b8c4d9"}}>Domaines, hébergement, DNS, transferts et facturation.</p></div><a href="/" style={{color:"#fff"}}>← Accueil</a></div><nav style={{display:"flex",gap:8,overflowX:"auto",padding:"20px 0"}}>{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} style={{padding:"11px 16px",borderRadius:999,border:"1px solid #29466f",background:tab===id?"#d4aa45":"#0d2346",color:tab===id?"#07152f":"#fff"}}>{label}</button>)}</nav>{msg&&<div style={{padding:14,background:"#15365e",borderRadius:12,marginBottom:16}}>{msg}</div>}<section style={{background:"#0d2346",border:"1px solid #203b67",borderRadius:18,padding:22}}>
{tab==="domains"&&<><h2>Mes domaines</h2>{domains.length?domains.map(d=><div key={d.id} style={{padding:"16px 0",borderBottom:"1px solid #203b67"}}><strong>{d.domain_name}</strong> <span style={{color:"#72d6a0"}}>{d.status}</span><div style={{marginTop:10}}><label>Auto-renouvellement <input type="checkbox" checked={d.auto_renew} onChange={()=>toggle(d.id,"auto_renew",d.auto_renew)}/></label> <label>Privacy <input type="checkbox" checked={d.privacy_enabled} onChange={()=>toggle(d.id,"privacy_enabled",d.privacy_enabled)}/></label></div></div>):<p>Aucun domaine enregistré.</p>}</>}
{tab==="cart"&&<><h2>Panier</h2>{cart.length?cart.map(i=><div key={i.domain} style={{display:"flex",justifyContent:"space-between",padding:14,borderBottom:"1px solid #203b67"}}><span>{i.domain} · {i.years} an</span><button onClick={()=>remove(i.domain)}>Supprimer</button></div>):<p>Panier vide.</p>}{cart.length>0&&<button onClick={checkout} style={{marginTop:18,padding:"12px 20px",border:0,borderRadius:10,background:"#d4aa45"}}>Passer la commande</button>}</>}
{tab==="hosting"&&<><h2>Hébergement Bickri</h2><button onClick={addSite} style={{padding:"12px 18px",border:0,borderRadius:10,background:"#d4aa45"}}>+ Créer un site</button>{sites.map(s=><div key={s.id} style={{padding:14,borderBottom:"1px solid #203b67"}}><strong>{s.host}</strong><div>{s.status} · {s.title}</div></div>)}</>}
{tab==="transfer"&&<><h2>Transfert de domaine</h2><p>Transférez un domaine vers Bickri avec son code d'autorisation.</p><a href="/transfer" style={{color:"#d4aa45"}}>Démarrer un transfert →</a></>}
{tab==="dns"&&<><h2>Gestion DNS</h2><p>API DNS prête pour A, AAAA, CNAME, MX, TXT, NS et CAA.</p></>}
{tab==="billing"&&<><h2>Facturation</h2><p>Les commandes, paiements et factures sont enregistrés dans Supabase.</p></>}</section></div></main>}